name: build

on: push

jobs:
  build_and_test:
    name: Run Maven build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build and test project
        run: mvn --batch-mode verify
