name: build

on: push

jobs:
  maven:
    name: Project build
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v2

      - name: JDK setup
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Maven build
        run: mvn --batch-mode verify
