name: sonar

on:
  push:
    branches:
      - 'master'
      - 'release/**'

jobs:
  sonarcloud:
    name: Static code analysis
    environment: default
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: SonarCloud analysis
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
